### PR TITLE
Orphaned Resources - cost saving - stopped and not deallocated VMs

### PR DESCRIPTION
**Pull request by TimWanierke**
AzGovViz run identifier: BE46DE4541B81741E494183AE5521C166266757339C9685EECCFE252C476BF265EB7AF55D185B1F2B7210A58E15DD8C45405C5A570DEA9308F911CFD8DB49F84

### CODE REVIEW

**Comment by JulianHayward** [comment]
great stuff. As a new intent 'cost savings - stopped but not deallocated VM' is introduced, some sections need to be aligned accordingly. Please check for occurrences of `-eq 'cost savings'` and replace with e.g. `-like 'cost savings*'`.  
As a result we should see related cost for stopped VMs in the HTML file (TenantSummary/Subscriptions, Resources & Defender/Orphaned Resources) and the *_ResourcesOrphaned.csv file.

**Comment by TimWanierke** [comment]
Updated the code with `-like 'cost savings*'`.
AzGovViz identifier: BE46DE4541B81741E494183AE5521C166266757339C9685EECCFE252C476BF265EB7AF55D185B1F2B7210A58E15DD8C45405C5A570DEA9308F911CFD8DB49F84

**Comment by TimWanierke** [comment]
Another small update on this PullRequest. I've adjusted the Query for "orphaned resources" - stopped VMs

AzGovViz indentifier:
BE46DE4541B81741E494183AE5521C166266757339C9685EECCFE252C476BF265EB7AF55D185B1F2B7210A58E15DD8C45405C5A570DEA9308F911CFD8DB49F84

**Comment by JulianHayward** [comment]
super, thanks!

**Pull request merged**
