### PR TITLE
Added support for -DoAzureConsumptionPreviousMonth

### PR DESCRIPTION
**Pull request by JanElholm**
Azure Governance Visualizer (6.4.3) run identifier: '7359F93897095F617BC027CE92431EDF32D350F657E902772331BDFA441DD2298358BF5F45B437CCF83A4FB797E214D59854D275421CD370321E2BCC4ADC1A6D'

### CODE REVIEW

**Comment by JulianHayward** [comment]
hey @JanElholm looks great!

One ask before I merge, would you also please update the [ado variables](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/blob/master/.azuredevops/pipelines/AzGovViz.variables.yml)?

May I challenge the scenario of using `DoAzureConsumptionPreviousMonth`  - that would basically mean that in the scenario where you execute azgvz per default schedule that e.g. on 31st of March, all March long executions did the same query with exact same results to have the consumption data from February? Can you elaborate a bit on the use case please?

**Comment by JanElholm** [comment]
Hey @JulianHayward 

Ado variables are updated now

Yes, we only aim at running the AzGovViz once a month (second or third day in the month) and would like to use it for reporting on the consumption from the previous month. Another option is to run AzGovViz with a consumption duration of 30 days, but that will not be precise when months have various length. Hope that explains our use case

**Comment by JulianHayward** [comment]
all right, understood. Please don´t set `DoAzureConsumptionPreviousMonth` as default (in the variables file you set it to true)

**Comment by JulianHayward** [comment]
sorry, could have been guiding better ..

this is how it should be:
```
  - name: DoAzureConsumptionPreviousMonth
    # Switch | example: value: true
    value:
```

**Comment by JanElholm** [comment]
Ah ok - thanks - updated now

**Comment by JulianHayward** [comment]
@JanElholm thanks for contribution

**Pull request merged**
